nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['%env(resolve:ALLOWED_ORIGINS)%']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Accept', 'Authorization', 'X-API-TOKEN']
        expose_headers: []
        max_age: 3600
        hosts: []
        origin_regex: false
        forced_allow_origin_value: null
