security:
    # password hasher
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: 'argon2id'
            memory_cost: 65536
            time_cost: 4

    # user entity providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # app firewalls
    firewalls:
        login:
            pattern: ^/api/auth/login
            stateless: true
            provider: app_user_provider
            json_login:
                username_path: email
                check_path: /api/auth/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            stateless: true
            jwt: ~
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    # app access manager 
    access_control:
        # public access routes
        - { path: ^/api/auth/register,      roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/login,         roles: PUBLIC_ACCESS }
        - { path: ^/api/doc,                roles: PUBLIC_ACCESS }

        # admin access routes
        - { path: ^/api/admin,              roles: ROLE_ADMIN }

        # user access routes
        - { path: ^/api,                    roles: ROLE_USER }   
