controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# auth login route (handled by JWT bundle)
api_login_check:
    path: /api/auth/login
    methods: [POST]

# handle not found error (in prod env)
when@prod:
    catch_all:
        path: /{any}
        controller: App\Controller\ErrorController::handleNotFoundError
        methods: ['GET']
        requirements:
            any: .*
